### ISSUE TITLE
Have trouble installing CitcomS

### ISSUE THREAD

**Issue by zbc1508** [geodynamics/citcoms#13]
Dear developers：
I have tried many times on installing CitcomS on my Mac M2 these months, but still can't use it.
I installed centOS7 virtual machine, and now I tried to use ubuntu 20.04 virtual machine, and it seemed still did't work. 
And I copy the terminal txt, could help me find the problems? Thank you very much!

lily@lily:~/software/CitcomS-3.3.1$ ls
aclocal.m4  ChangeLog     COPYING   lib          NEWS    visual
AUTHORS     config.h.in   etc       m4           Py2C
aux-config  configure     examples  Makefile.am  README
bin         configure.ac  INSTALL   Makefile.in  tests
lily@lily:~/software/CitcomS-3.3.1$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for mpicc... mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether mpicc accepts -g... yes
checking for mpicc option to accept ISO C89... none needed
checking whether mpicc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of mpicc... gcc3
checking for mpicxx... mpicxx
checking whether we are using the GNU C++ compiler... yes
checking whether mpicxx accepts -g... yes
checking dependency style of mpicxx... gcc3
checking how to run the C preprocessor... mpicc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by mpicc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from mpicc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if mpicc supports -fno-rtti -fno-exceptions... no
checking for mpicc option to produce PIC... -fPIC -DPIC
checking if mpicc PIC flag -fPIC -DPIC works... yes
checking if mpicc static flag -static works... no
checking if mpicc supports -c -o file.o... yes
checking if mpicc supports -c -o file.o... (cached) yes
checking whether the mpicc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... mpicxx -E
checking for ld used by mpicxx... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the mpicxx linker (/usr/bin/ld) supports shared libraries... yes
checking for mpicxx option to produce PIC... -fPIC -DPIC
checking if mpicxx PIC flag -fPIC -DPIC works... yes
checking if mpicxx static flag -static works... no
checking if mpicxx supports -c -o file.o... yes
checking if mpicxx supports -c -o file.o... (cached) yes
checking whether the mpicxx linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing MPI_Init... none required
checking for library containing H5Fopen... no
configure: WARNING: HDF5 library not found; disabling HDF5 support
checking mpi.h usability... yes
checking mpi.h presence... yes
checking for mpi.h... yes
checking for library containing gzopen... -lz
checking for library containing sqrt... -lm
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bin/Makefile
config.status: creating etc/Makefile
config.status: creating examples/Makefile
config.status: creating lib/Makefile
config.status: creating tests/Makefile
config.status: creating Py2C/Makefile
config.status: creating visual/Makefile
config.status: creating visual/OpenDXMacro/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

================ Configuration Summary ================
	 CC:  mpicc
	 CFLAGS:  -g -O2
	 CPPFLAGS:  -DUSE_GZDIR
	 LDFLAGS: 
	 LIBS:  -lm -lz
	 with-hdf5:  no
	 with-ggrd:  no
lily@lily:~/software/CitcomS-3.3.1$ make
make  all-recursive
make[1]: Entering directory '/home/lily/software/CitcomS-3.3.1'
Making all in Py2C
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1/Py2C'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1/Py2C'
Making all in etc
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1/etc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1/etc'
Making all in examples
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1/examples'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1/examples'
Making all in tests
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1/tests'
Making all in visual
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1/visual'
Making all in OpenDXMacro
make[3]: Entering directory '/home/lily/software/CitcomS-3.3.1/visual/OpenDXMacro'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/lily/software/CitcomS-3.3.1/visual/OpenDXMacro'
make[3]: Entering directory '/home/lily/software/CitcomS-3.3.1/visual'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/lily/software/CitcomS-3.3.1/visual'
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1/visual'
Making all in lib
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1/lib'
Making all in bin
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1/bin'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1/bin'
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1'
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1'
make[1]: Leaving directory '/home/lily/software/CitcomS-3.3.1'
lily@lily:~/software/CitcomS-3.3.1$ make install
Making install in Py2C
make[1]: Entering directory '/home/lily/software/CitcomS-3.3.1/Py2C'
make[2]: Entering directory '/home/lily/software/CitcomS-3.3.1/Py2C'
 /usr/bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c Py2C '/usr/local/bin'
libtool: install: /usr/bin/install -c Py2C /usr/local/bin/Py2C
/usr/bin/install: cannot create regular file '/usr/local/bin/Py2C': Permission denied
make[2]: *** [Makefile:377: install-binPROGRAMS] Error 1
make[2]: Leaving directory '/home/lily/software/CitcomS-3.3.1/Py2C'
make[1]: *** [Makefile:595: install-am] Error 2
make[1]: Leaving directory '/home/lily/software/CitcomS-3.3.1/Py2C'
make: *** [Makefile:400: install-recursive] Error 1
lily@lily:~/software/CitcomS-3.3.1$

**Comment by tan2** [comment]
Hi Lily,

You have successfully compiled CitcomS. You don't need to run "make
install". You can find the executable in the directory
"~/software/CitcomS-3.3.1/bin/".

**Comment by zbc1508** [comment]
I see. Thank you for your reply！
