### ISSUE TITLE
How to set parameters if I want to integrate backward in time?

### ISSUE THREAD

**Issue by wkillers** [geodynamics/citcoms#6]
I want to run the CitcomS code backward in time from a given initial temperature, which parameters do I need to set? I found two parameters, i.e., the Rayleigh number Ra, and the inputdiffusivity. Do I need to set Ra to be negative and also inputdiffusivity=-1 (which is 1 in User Manual)? Is there any other parameter I need to modify?

Thanks.

**Comment by tan2** [comment]
Set Ra to be negative. And set inputdiffusivity to something small, maybe
around 0.1. More information can be found in this paper:

Conrad and Gurnis (2003), G^3, Seismic tomography, surface uplift, and the
breakup of Gondwanaland: Integrating mantle convection backwards in time

**Comment by wkillers** [comment]
Thanks.
