### ISSUE TITLE
subduciton geometry

### ISSUE THREAD

**Issue by Ubun1** [geodynamics/citcoms#7]
hello! 
i want to reproduce experiments from this article ["Continental underplating after slab break-off"](https://goo.gl/x7MkXJ). But there are too few information about how to set various subduction geometry and attach different reology parametrs to different layers of model. 
Maybe someone can help me with some more comprehensive guides or advise articles where this information  exist?

**Comment by tan2** [comment]
This type of question should be posted on the user forum instead:
https://community.geodynamics.org/c/mantle-convection/12
